### ISSUE TITLE
CB: Praxis-Beispiele nachreichen

### ISSUE THREAD

**Issue by ZeroPointMax** [importPI19fromDHGE/dhge-pi19-sem6#24]
> Irgendwie fehlt mir noch etwas wo man ein Beispiel hätte. Man könnte evtl noch auf die Beispiele von Kusche verlinken oder gar einchecken. (siehe [cal.y](https://computerix.info/examples/cal.y), [cal.lex](https://computerix.info/examples/cal.lex))

Stimmt, das würde ich ggf. als eigene PR nachreichen

_Originally posted by @ZeroPointMax in https://github.com/importPI19fromDHGE/dhge-pi19-sem6/issues/20#issuecomment-1044058681_

**Comment by Steve2955** [comment]
@ZeroPointMax Ich glaube das wird nichts mehr 😅
