### ISSUE TITLE
Anki Action 2.0

### ISSUE THREAD

**Issue by Steve2955** [importPI19fromDHGE/dhge-pi19-sem6#3]
[ausstehendes Issue aus Sem5](https://github.com/importPI19fromDHGE/dhge-pi19-sem5/issues/118), daher bisher keine Anki Action in diesem Repo.

**Comment by photovoltex** [comment]
https://github.com/importPI19fromDHGE/dhge-pi19-sem5/issues/118#issuecomment-1034673314

**Comment by nukerxy** [comment]
bump. Gibt's Einwände, machen wir es so?
Meinung @ZeroPointMax @Steve2955?; Oliver und ich fänden es gut - anhand der Reactions

**Comment by RvNovae** [comment]
> Ich habe einen Moment darüber nachgedacht. Mit Felix Vorschlag kommen so Sachen wie ISR.pdf.anki.md raus, wenn das Dokument sowohl PDF als auch ANKI-Deck sein soll.

Das fänd ich an sich in Ordnung aber dein Vorschlag klingt auch nicht verkehrt.

**Comment by nukerxy** [comment]
Nur README.md wird automatisch gerendet https://github.com/importPI19fromDHGE/dhge-pi19-sem6/commit/6158a10674945a592b4508ccdbc8ed79f3011d6b

**Comment by Steve2955** [comment]
> Nur `README.md `wird automatisch gerendet [6158a10](https://github.com/importPI19fromDHGE/dhge-pi19-sem6/commit/6158a10674945a592b4508ccdbc8ed79f3011d6b)

Dateilisten sollte die einfachste Lösung sein.

**Comment by RvNovae** [comment]
> > Nur `README.md `wird automatisch gerendet [6158a10](https://github.com/importPI19fromDHGE/dhge-pi19-sem6/commit/6158a10674945a592b4508ccdbc8ed79f3011d6b)
> 
> Ich denke wir sollten einfach auf Dateilisten zurückgreifen.

Ist wahrscheinlich am einfachsten und übersichtlichsten.

**Comment by RvNovae** [comment]
> Alternative: README.md werden als PDF gerendert, und daraus werden Anki-Files erstellt. Alle weiteren PDF werden in Dateilisten definiert. Dateien im anki-Directory sind Anki-Decks
> 
> ```
> Modul/
> ├── appendix/
> ├── assets/
> ├── anki/
> │      ├── LKF.md
> │      └── Glossar.md
> └── README.md
> ```

Also wenn wir eh Dateilisten haben, können wir auch gleich alles darüber steuern.

**Comment by nukerxy** [comment]
---  wir machen Dateilisten ---

**Comment by RvNovae** [comment]
Sollte der issue nicht offen bleiben, bis das umgesetzt ist?

**Comment by Steve2955** [comment]
> Sollte der issue nicht offen bleiben, bis das umgesetzt ist?

Ja

**Comment by ZeroPointMax** [comment]
> Ich spüre eine gewisse Anspannung

Wir sind bei 12V und 1 Fork
