### ISSUE TITLE
Ein MPP-II-Anki-Deck

### ISSUE THREAD

**Issue by jsuesse** [importPI19fromDHGE/dhge-pi19-sem6#46]
### Variante A (mein Favorit)
Deck mit wichtigen / typischen Themen erstellen, dieses Deck soll nur neue Themen der letzten beiden Semester enthalten.
Das MPP I-Deck aus Sem4 separat.

### Variante B

Ein gemeinsames Deck, MPP I + neue Fragen = MPP II

### Inhalt: 

Welche sind die relevanten Module der letzten beiden Semester?

**nicht relevant**
WPM II und III im Allgemeinen
Consulting - (CONS) - Müller
neuronale Netze und maschinelles Lernen - (ML) - Feldmann
Forensik - (PRO) - Strassburg
Graphische Datenverarbeitung - (GDV) - Herbst
e-Commerce - (WEB) - Müller (**?**)
ABWL 1&2 - Leder

**relevant**
IT-Sicherheit und Co. - (ISR) - Müller
Rechnernetze - (NET) - Barié
Verteilte Systeme - (NET) - Feldmann
Systemadministration - (RES) - Günther (Für PIB)
Entwicklung von Webanwendungen - (WEB) - Grimm (**?**)
Kusches WPM, wenn man teilgenommen hat

Bitte diskutieren! 

### Ordner-Struktur

orientieren an [Sem 4](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/tree/main/MPP-PI)
Datei-Skelett folgt

LG

**Comment by Steve2955** [comment]
WPM ist bei Günther als Prüfer auf jeden zu 100% relevant.

Ich sehe irgendwie das Problem, dass sich die Schwerpunkte und Ansprüche sehr stark zwischen der Prüfungskommission aus Kusche und Günther unterscheiden werden.

**Comment by Steve2955** [comment]
Aber ansonsten würde ich das MPP1-Deck auch erstmal 1:1 übernehmen und nur ergänzen. Mit mehreren Decks habe ich kein Problem, das empfinde ich auch eher als positiv.
